# Generated by Django 6.1.1 on 2026-09-13 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('property_type', models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('house', 'خانه'), ('land', 'زمین'), ('office', 'دفتر کار'), ('shop', 'مغازه'), ('commercial', 'ملک تجاری'), ('warehouse', 'انبار')], max_length=30)),
                ('deal_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('mortgage', 'رهن'), ('rent_mortgage', 'رهن و اجاره')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('area', models.PositiveIntegerField(help_text='متراژ به متر مربع')),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('floor', models.IntegerField(default=0)),
                ('total_floors', models.PositiveSmallIntegerField(default=0)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('units_per_floor', models.PositiveSmallIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('price_per_meter', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('parking', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('central_heating', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'موجود'), ('reserved', 'رزرو شده'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده'), ('inactive', 'غیرفعال')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='properties.property')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='properties__propert_5c7790_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['deal_type'], name='properties__deal_ty_1ccd6e_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city'], name='properties__city_74fa1a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['neighborhood'], name='properties__neighbo_490602_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['area'], name='properties__area_f9d971_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status'], name='properties__status_6427a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'property'), name='unique_user_property_favorite'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyfeature',
            unique_together={('property', 'name')},
        ),
    ]
